// Auto-generated by scripts/build-gallery.js – do not edit by hand
window.GALLERY_IMAGES = [
  {
    "image": "images/0825C01F-6FA7-40E6-8305-BA16CE97F12C.jpeg",
    "message": ""
  },
  {
    "image": "images/0E5B21CA-EAA6-4521-8A4C-1E8E3CF7422D.jpeg",
    "message": ""
  },
  {
    "image": "images/10CC7921-D5B4-4233-BD06-A86936F7BA8D.jpeg",
    "message": ""
  },
  {
    "image": "images/156BAF6D-13FB-4CF8-A025-E92236DFB7E7.jpeg",
    "message": ""
  },
  {
    "image": "images/15FFECE3-D4A9-42C9-9111-C81CA397A566.jpeg",
    "message": ""
  },
  {
    "image": "images/16B847D6-0CE6-46CA-9A9F-090FEACB33C1.jpeg",
    "message": ""
  },
  {
    "image": "images/170D0667-016A-4D11-A698-676499F3F421.jpeg",
    "message": ""
  },
  {
    "image": "images/18E619BF-B84B-4B03-8FE1-16F722F9E7FA.jpeg",
    "message": ""
  },
  {
    "image": "images/1C3D9A8A-D0EC-418C-A3CA-71471633A348.jpeg",
    "message": ""
  },
  {
    "image": "images/1F771F97-4404-4900-B7C1-40C0B9984603.jpeg",
    "message": ""
  },
  {
    "image": "images/239FCDD0-3673-40A8-86A6-D36574587279.jpeg",
    "message": ""
  },
  {
    "image": "images/2DA84AF2-43D0-4305-BF60-E571AADC200A.jpeg",
    "message": ""
  },
  {
    "image": "images/33A3F877-F8E6-48B3-A694-BC890377EA13.jpeg",
    "message": ""
  },
  {
    "image": "images/39DCF20C-0698-45B0-825E-32348A37AC88.jpeg",
    "message": ""
  },
  {
    "image": "images/3F8BAD86-AB03-4A92-8CF6-A1CD690ECF45.jpeg",
    "message": ""
  },
  {
    "image": "images/416EAE44-C2B3-48BA-B4D1-E2CC048F0F2D.jpeg",
    "message": ""
  },
  {
    "image": "images/4A5B03CD-44BD-45B6-91E5-49E728028A6B.jpeg",
    "message": ""
  },
  {
    "image": "images/65C24CBF-871C-4714-9DC8-078541871F0C.jpeg",
    "message": ""
  },
  {
    "image": "images/6654293D-9373-4797-A379-A44235BB9B2C.jpeg",
    "message": ""
  },
  {
    "image": "images/70060078-C39A-48BD-8776-DDDAC531481E.jpeg",
    "message": ""
  },
  {
    "image": "images/733C2BA3-B96B-456A-B1AA-766357CA53E9.jpeg",
    "message": ""
  },
  {
    "image": "images/8DDCFCEC-4B4A-4790-AAE7-D4808977D9BA.jpeg",
    "message": ""
  },
  {
    "image": "images/9002ACA1-8C63-4B19-8984-51FC20B6B4FC.jpeg",
    "message": ""
  },
  {
    "image": "images/98BD94F0-F467-42F9-B4B0-7E938DBAFD4E.jpeg",
    "message": ""
  },
  {
    "image": "images/98F8E4E3-A8C8-45D7-9712-BB826C904A18.jpeg",
    "message": ""
  },
  {
    "image": "images/A909531F-9CB0-4DF6-9FF7-F1FCA6C8A5C2.jpeg",
    "message": ""
  },
  {
    "image": "images/AED9738E-19B6-41D7-8B73-F7C6AB453AC8.jpeg",
    "message": ""
  },
  {
    "image": "images/B80FA1B0-4614-46D6-AAC8-B4C3A425351C.jpeg",
    "message": ""
  },
  {
    "image": "images/B9EDDB0D-1B71-4D06-849A-051780889E57.jpeg",
    "message": ""
  },
  {
    "image": "images/BB5D57CD-17B1-41E8-A915-DB8D06E13140.jpeg",
    "message": ""
  },
  {
    "image": "images/CACEB65C-19D5-4ABB-B20C-A21CAF381A8F.jpeg",
    "message": ""
  },
  {
    "image": "images/DE194D23-4AB1-40E7-ABCF-3043ABC94D00.jpeg",
    "message": ""
  },
  {
    "image": "images/E527E2CE-FE5F-49A8-9454-516B37F4AAE9.jpeg",
    "message": ""
  },
  {
    "image": "images/EE1FB82F-647A-448D-A5DD-D7DAF0692CCE.jpeg",
    "message": ""
  },
  {
    "image": "images/EE67536C-5276-4FBB-93B6-6BBFB4F4E8EC.jpeg",
    "message": ""
  },
  {
    "image": "images/F904B7FA-F39C-4D64-99A7-3E6D865AB43B.jpeg",
    "message": ""
  },
  {
    "image": "images/FB8B20EA-64DA-429F-B1AA-0A08E5C5EC37.jpeg",
    "message": ""
  },
  {
    "image": "images/FC79085D-00D9-48AE-9055-4955B97BFC4B.jpeg",
    "message": ""
  },
  {
    "image": "images/FF80F567-FBE7-41C4-B644-DF9A85B4E280.jpeg",
    "message": ""
  },
  {
    "image": "images/horse.jfif",
    "message": ""
  },
  {
    "image": "images/letter.jpeg",
    "message": ""
  },
  {
    "image": "images/libby.jpeg",
    "message": ""
  }
];
