/**
 * Scans the images folder and generates gallery-data.js with all image files.
 * Run from project root: node scripts/build-gallery.js
 * Excludes: .gitkeep, videos (.mp4, .webm, .mov), and non-image files.
 */

const fs = require('fs');
const path = require('path');

const IMAGES_DIR = path.join(__dirname, '..', 'images');
const OUTPUT_FILE = path.join(__dirname, '..', 'gallery-data.js');
const IMAGE_EXT = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.jfif', '.bmp'];
const VIDEO_EXT = ['.mp4', '.webm', '.mov', '.avi'];

function buildGallery() {
  if (!fs.existsSync(IMAGES_DIR)) {
    console.error('Images folder not found:', IMAGES_DIR);
    process.exit(1);
  }

  const files = fs.readdirSync(IMAGES_DIR);
  const items = [];

  for (const file of files) {
    if (file === '.gitkeep') continue;
    const ext = path.extname(file).toLowerCase();
    if (VIDEO_EXT.includes(ext)) continue;
    if (!IMAGE_EXT.includes(ext)) continue;
    const imagePath = 'images/' + file;
    items.push({ image: imagePath, message: '' });
  }

  items.sort((a, b) => a.image.localeCompare(b.image));

  const js = `// Auto-generated by scripts/build-gallery.js – do not edit by hand\n` +
    `window.GALLERY_IMAGES = ${JSON.stringify(items, null, 2)};\n`;

  fs.writeFileSync(OUTPUT_FILE, js, 'utf8');
  console.log('Wrote', items.length, 'images to gallery-data.js');
}

buildGallery();
